name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { ruby: "2.7", rails: "6.1.7", grape-swagger: "1.6.1" }
          - { ruby: "3.0", rails: "6.1.7", grape-swagger: "1.6.1" }
          - { ruby: "3.1", rails: "6.1.7", grape-swagger: "1.6.1" }
          - { ruby: "3.1", rails: "7.2.1", grape-swagger: "1.6.1" }
          - { ruby: "3.2", rails: "6.1.7", grape-swagger: "1.6.1" }
          - { ruby: "3.2", rails: "6.1.7", grape-swagger: "2.1.1" }
          - { ruby: "3.2", rails: "7.2.1", grape-swagger: "1.6.1" }
          - { ruby: "3.2", rails: "7.2.1", grape-swagger: "2.1.1" }
          - { ruby: "3.3", rails: "6.1.7", grape-swagger: "1.6.1" }
          - { ruby: "3.3", rails: "6.1.7", grape-swagger: "2.1.1" }
          - { ruby: "3.3", rails: "7.2.1", grape-swagger: "1.6.1" }
          - { ruby: "3.3", rails: "7.2.1", grape-swagger: "2.1.1" }
          - { ruby: "jruby-9.4", rails: "6.1.7", grape-swagger: "1.6.1" }
          - { ruby: "jruby-9.4", rails: "6.1.7", grape-swagger: "2.1.1" }
          - { ruby: "jruby-9.4", rails: "7.2.1", grape-swagger: "1.6.1" }
          - { ruby: "jruby-9.4", rails: "7.2.1", grape-swagger: "2.1.1" }
    env:
      GRAPE_SWAGGER_VERSION: ${{ matrix.entry.grape-swagger }}
      RAILS_VERSION: ${{ matrix.entry.rails }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
          bundler-cache: true
      - name: Print Bundler Versions
        run: bundle show
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: "130.0"
      - uses: browser-actions/setup-geckodriver@latest
        with:
          geckodriver-version: "0.35.0"
      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: bundle exec rake spec
